name: CI Load Test

on:
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # kind setup k8s cluster in runners local  
      - name: Set up KinD cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: "v0.20.0"
          config: kindCluster.yaml

      # deploy ingress controller to kind k8s cluster        
      - name: Install Ingress Controller
        run: |
          kubectl apply -f nginxIngress.yaml
          
          label_selector="app.kubernetes.io/name=ingress-nginx,app.kubernetes.io/component=controller"
          duration=$((10 * 60))  
          interval=30            
          start_time=$(date +%s)

          while [ $(($(date +%s) - start_time)) -lt "$duration" ]; do
            kubectl get pods -n ingress-nginx 

            kubectl describe pod -l "$label_selector" -n ingress-nginx
            
            sleep $interval
          done          
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=90s

